name: stripe_payment
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more.
version: 1.0.9
homepage: https://github.com/jonasbark/flutter_stripe_payment

dependencies:
  build_runner: ^2.1.7
  json_annotation:  ^4.4.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.jonasbark.stripe_payment
        pluginClass: StripePaymentPlugin
      ios:
        pluginClass: StripePaymentPlugin

dev_dependencies:
  json_serializable: ^6.1.4
  flutter_test:
    sdk: flutter
  integration_test: ^0.8.0
  http: ^0.13.4
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
